### ISSUE TITLE
Push to Code for Philly account

### ISSUE THREAD

**Issue by flibbertigibbet** [melleio/cycle_#1]

**Comment by emelleme** [comment]
@flibbertigibbet the code for philly is slightly different; this is more a "getting started" version.

**Comment by flibbertigibbet** [comment]
Okay, the repos should have different names then.  It should go to the CfA account though.  People are going to expect to find this where the mobile repos are, and we need the org's central management.

**Comment by emelleme** [comment]
good call @flibbertigibbet. Updated name on the cfp account. I am going to publish and link versions of the android and ios here; and update the repos on cfp to reflect the cyclephilly versions.
